# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-11-07T08:17:09+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Track(BaseModel):
    """Represents a music track with complete metadata and file information.
    
    Includes basic track information (title, artist, album), musical properties
    (BPM, key, genre, mood), file details (path, format, size, bitrate), and
    playback statistics (play count, last played timestamp).
    """
    id: Optional[UUID] = None
    title: Optional[str] = None
    artist: Optional[str] = None
    album: Optional[str] = None
    year: Optional[int] = None
    genre: Optional[str] = None
    mood: Optional[str] = None
    bpm: Optional[int] = None
    key: Optional[str] = None
    duration: Optional[int] = Field(None, description='Duration in seconds')
    file_path: Optional[str] = None
    file_size: Optional[int] = Field(None, description='File size in bytes')
    file_format: Optional[str] = Field(None, example='mp3')
    bitrate: Optional[int] = None
    sample_rate: Optional[int] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    last_played: Optional[datetime] = None
    play_count: Optional[int] = None
    metadata_complete: Optional[bool] = None


class TrackCreate(BaseModel):
    """Schema for creating a new track in the library.
    
    Requires a file_path and allows optional metadata fields to be set
    during track creation.
    """
    file_path: str
    title: Optional[str] = None
    artist: Optional[str] = None
    album: Optional[str] = None
    year: Optional[int] = None
    genre: Optional[str] = None
    mood: Optional[str] = None
    bpm: Optional[int] = None
    key: Optional[str] = None


class TrackUpdate(BaseModel):
    """Schema for updating track metadata.
    
    All fields are optional, allowing partial updates to track information
    without requiring all fields to be provided.
    """
    title: Optional[str] = None
    artist: Optional[str] = None
    album: Optional[str] = None
    year: Optional[int] = None
    genre: Optional[str] = None
    mood: Optional[str] = None
    bpm: Optional[int] = None
    key: Optional[str] = None


class DetectedMetadata(BaseModel):
    """Metadata detected from audio file analysis.
    
    Contains technical audio properties that can be automatically extracted
    from the audio file itself, such as BPM, key, duration, sample rate, and bitrate.
    """
    bpm: Optional[int] = None
    key: Optional[str] = None
    duration: Optional[int] = None
    sample_rate: Optional[int] = None
    bitrate: Optional[int] = None


class ConfidenceScores(BaseModel):
    """Confidence scores for detected metadata values.
    
    Provides reliability scores (typically 0.0 to 1.0) for automatically
    detected metadata fields, indicating how confident the detection algorithm
    is in the accuracy of each value.
    """
    bpm: Optional[float] = None
    key: Optional[float] = None


class MetadataAnalysis(BaseModel):
    """Results of metadata analysis for an audio file.
    
    Contains the detected metadata from audio analysis along with confidence
    scores indicating the reliability of the detected values.
    """
    file_path: Optional[str] = None
    detected_metadata: Optional[DetectedMetadata] = None
    confidence_scores: Optional[ConfidenceScores] = None


class Playlist(BaseModel):
    """Represents a playlist with summary information.
    
    Contains playlist metadata including name, description, track count,
    total duration, and timestamps for creation and updates.
    """
    id: Optional[UUID] = None
    name: Optional[str] = None
    description: Optional[str] = None
    track_count: Optional[int] = None
    total_duration: Optional[int] = Field(None, description='Total duration in seconds')
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class PlaylistDetail(Playlist):
    """Extended playlist model that includes the list of tracks.
    
    Inherits all fields from Playlist and adds the full list of Track objects
    that belong to this playlist.
    """
    tracks: Optional[List[Track]] = None


class LibraryOverview(BaseModel):
    """Summary statistics and overview of the entire music library.
    
    Provides aggregated information about the library including total tracks,
    duration, size, genre count, average BPM, most common key, and metadata
    completeness metrics.
    """
    total_tracks: Optional[int] = None
    total_duration: Optional[int] = Field(None, description='Total duration in seconds')
    total_size: Optional[int] = Field(None, description='Total size in bytes')
    total_genres: Optional[int] = None
    average_bpm: Optional[float] = None
    most_common_key: Optional[str] = None
    metadata_completeness: Optional[float] = Field(
        None, description='Percentage of tracks with complete metadata'
    )
    tracks_missing_metadata: Optional[int] = None


class Pagination(BaseModel):
    """Pagination metadata for paginated API responses.
    
    Contains information about the current page, page size, total pages,
    total items, and navigation flags for previous/next pages.
    """
    page: Optional[int] = None
    size: Optional[int] = None
    total_pages: Optional[int] = None
    total_items: Optional[int] = None
    has_next: Optional[bool] = None
    has_previous: Optional[bool] = None
