#!/bin/bash

# Script to populate refdata table with diverse music library filter values
# Usage: ./populate_refdata.sh

BASE_URL="http://127.0.0.1:8000/refdata/trackfilters"

echo "Populating refdata table with diverse filter values..."
echo ""

# Genre - Diverse music genres from around the world (111 genres)
echo "Adding genres..."
curl -X POST "${BASE_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "key": "genre",
    "value": [
      "Aboriginal",
      "Afrobeat",
      "Afrobeats",
      "Afro-fusion",
      "Alternative",
      "Amapiano",
      "Ambient",
      "Apala",
      "Arabesque",
      "Arabic Pop",
      "Azonto",
      "Bachata",
      "Baile Funk",
      "Balkan",
      "Bhangra",
      "Blues",
      "Bluegrass",
      "Bollywood",
      "Bongo Flava",
      "Bossa Nova",
      "C-Pop",
      "Cajun",
      "Calypso",
      "Cantopop",
      "Carnatic",
      "Celtic",
      "Chaabi",
      "City Pop",
      "Classical",
      "Country",
      "Coupé-Décalé",
      "Cumbia",
      "Dabke",
      "Dancehall",
      "Dangdut",
      "Desert Blues",
      "Drill",
      "Dub",
      "Dubstep",
      "EDM",
      "Electronic",
      "Enka",
      "Ethiopian Jazz",
      "Fado",
      "Filmi",
      "Flamenco",
      "Folk",
      "Forro",
      "Fuji",
      "Funk",
      "Gamelan",
      "Gnawa",
      "Gospel",
      "Gqom",
      "Grime",
      "Highlife",
      "Hindi Pop",
      "Hindustani",
      "Hip-Hop",
      "Hiplife",
      "House",
      "Indie",
      "J-Pop",
      "Jazz",
      "Juju",
      "K-Pop",
      "Khaleeji",
      "Kizomba",
      "Klezmer",
      "Kompa",
      "Kuduro",
      "Kwaito",
      "Latin",
      "Makossa",
      "Mandopop",
      "Mbalax",
      "Merengue",
      "Metal",
      "OPM",
      "P-Pop",
      "Pagode",
      "Persian Pop",
      "Polynesian",
      "Pop",
      "Punk",
      "Qawwali",
      "R&B",
      "Rai",
      "Rap",
      "Rebetiko",
      "Reggae",
      "Reggae Fusion",
      "Reggaeton",
      "Rock",
      "Rumba",
      "Salsa",
      "Samba",
      "Semba",
      "Sertanejo",
      "Shangaan Electro",
      "Ska",
      "Soca",
      "Soul",
      "Soukous",
      "T-Pop",
      "Tango",
      "Techno",
      "Thai Pop",
      "Touareg",
      "Trance",
      "Trap",
      "Turkish Pop",
      "Worldbeat",
      "Zouk",
      "Zydeco"
    ]
  }'
echo -e "\n"

# Mood - Comprehensive emotional and energy-based moods (98 moods)
echo "Adding moods..."
curl -X POST "${BASE_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "key": "mood",
    "value": [
      "Adventurous",
      "Aggressive",
      "Angry",
      "Anxious",
      "Bittersweet",
      "Blissful",
      "Bouncy",
      "Calm",
      "Celebratory",
      "Cheerful",
      "Chill",
      "Confident",
      "Contemplative",
      "Dark",
      "Defiant",
      "Depressed",
      "Determined",
      "Dramatic",
      "Dreamy",
      "Eerie",
      "Emotional",
      "Empowering",
      "Energetic",
      "Euphoric",
      "Excited",
      "Fearful",
      "Festive",
      "Fierce",
      "Flirtatious",
      "Funky",
      "Futuristic",
      "Gentle",
      "Gloomy",
      "Grateful",
      "Gritty",
      "Groovy",
      "Happy",
      "Haunting",
      "Heartbroken",
      "Hopeful",
      "Hypnotic",
      "Inspiring",
      "Intense",
      "Intimate",
      "Introspective",
      "Joyful",
      "Laid-back",
      "Lively",
      "Lonely",
      "Longing",
      "Loving",
      "Meditative",
      "Melancholic",
      "Mellow",
      "Mischievous",
      "Motivational",
      "Mysterious",
      "Nostalgic",
      "Optimistic",
      "Passionate",
      "Patriotic",
      "Peaceful",
      "Pensive",
      "Playful",
      "Poignant",
      "Powerful",
      "Proud",
      "Rebellious",
      "Reflective",
      "Regretful",
      "Relaxed",
      "Romantic",
      "Sad",
      "Sarcastic",
      "Sensual",
      "Sentimental",
      "Serene",
      "Serious",
      "Sexy",
      "Smooth",
      "Somber",
      "Sophisticated",
      "Soulful",
      "Spiritual",
      "Spooky",
      "Sultry",
      "Suspenseful",
      "Sweet",
      "Tender",
      "Tense",
      "Thoughtful",
      "Thrilling",
      "Triumphant",
      "Upbeat",
      "Uplifting",
      "Victorious",
      "Vulnerable",
      "Wistful",
      "Yearning"
    ]
  }'
echo -e "\n"

# Key - All musical keys in both sharp and flat notations (34 keys)
echo "Adding musical keys..."
curl -X POST "${BASE_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "key": "key",
    "value": [
      "A",
      "A#",
      "A#m",
      "Ab",
      "Abm",
      "Am",
      "B",
      "Bb",
      "Bbm",
      "Bm",
      "C",
      "C#",
      "C#m",
      "Cm",
      "D",
      "D#",
      "D#m",
      "Db",
      "Dbm",
      "Dm",
      "E",
      "Eb",
      "Ebm",
      "Em",
      "F",
      "F#",
      "F#m",
      "Fm",
      "G",
      "G#",
      "G#m",
      "Gb",
      "Gbm",
      "Gm"
    ]
  }'
echo -e "\n"

# BPM Ranges - Granular BPM ranges with descriptive labels (15 ranges)
echo "Adding BPM ranges..."
curl -X POST "${BASE_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "key": "bpm",
    "value": [
      "40-59 BPM (Very Slow)",
      "60-69 BPM (Slow)",
      "70-79 BPM (Ballad)",
      "80-89 BPM (Mid-Slow)",
      "90-99 BPM (Moderate)",
      "100-109 BPM (Mid-Tempo)",
      "110-119 BPM (Upbeat)",
      "120-129 BPM (Dance)",
      "130-139 BPM (Energetic)",
      "140-149 BPM (Fast)",
      "150-159 BPM (Very Fast)",
      "160-169 BPM (Rapid)",
      "170-179 BPM (Drum & Bass)",
      "180-199 BPM (Breakbeat)",
      "200+ BPM (Extreme)"
    ]
  }'
echo -e "\n"

# Year - Decades from 1920s to 2030s (12 decades)
echo "Adding year ranges..."
curl -X POST "${BASE_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "key": "year",
    "value": [
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s",
      "2030s"
    ]
  }'
echo -e "\n"

# Artist - Major artists from Nigeria, US, UK, and South Africa (alphabetically ordered)
echo "Adding major artists..."
curl -X POST "${BASE_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "key": "artist",
    "value": [
      "21 Savage",
      "6LACK",
      "Adele",
      "Adekunle Gold",
      "AKA",
      "Ami Faku",
      "Anitta",
      "Ariana Grande",
      "Asake",
      "Ayra Starr",
      "Bad Bunny",
      "Beyoncé",
      "Billie Eilish",
      "Black Coffee",
      "Black Sherif",
      "Blxckie",
      "Blaqbonez",
      "Bryson Tiller",
      "Burna Boy",
      "Busta 929",
      "Cassper Nyovest",
      "Central Cee",
      "Ckay",
      "Coi Leray",
      "Davido",
      "DBN Gogo",
      "DJ Maphorisa",
      "DJ Speedsta",
      "Don Toliver",
      "Doja Cat",
      "Drake",
      "Dua Lipa",
      "Ed Sheeran",
      "Eminem",
      "Fireboy DML",
      "Focalistic",
      "Frank Ocean",
      "Future",
      "Gyakie",
      "Harry Styles",
      "J. Cole",
      "J Hus",
      "JAE5",
      "Joeboy",
      "Jorja Smith",
      "Kabza De Small",
      "Kendrick Lamar",
      "Kizz Daniel",
      "Lady Du",
      "Lil Baby",
      "Lil Durk",
      "Lil Uzi Vert",
      "Lojay",
      "Major League Djz",
      "Makhadzi",
      "Master KG",
      "Mayorkun",
      "Megan Thee Stallion",
      "Mellow & Sleazy",
      "Mnike",
      "Nasty C",
      "Naira Marley",
      "Nicki Minaj",
      "Niniola",
      "Omah Lay",
      "Oxlade",
      "Olamide",
      "PinkPantheress",
      "Post Malone",
      "Rayvanny",
      "Rema",
      "Ruger",
      "Sauti Sol",
      "Seyi Vibez",
      "Sho Madjozi",
      "Skepta",
      "Stonebwoy",
      "Stormzy",
      "SZA",
      "Tems",
      "The Weeknd",
      "Tiwa Savage",
      "Travis Scott",
      "Tyla",
      "Tyler, The Creator",
      "Usher",
      "Victony",
      "Wande Coal",
      "Wizkid",
      "Young Jonn",
      "Yung Bleu",
      "Zinoleesky"
    ]
  }'
echo -e "\n"

echo "Refdata population complete!"
echo "Total entries added:"
echo "  - 111 Genres (globally diverse)"
echo "  - 98 Moods (comprehensive emotional range)"
echo "  - 34 Musical Keys (sharp and flat notations)"
echo "  - 15 BPM Ranges (granular tempo classifications)"
echo "  - 12 Year Ranges (1920s-2030s)"
echo "  - 93 Artists (Nigeria, US, UK, South Africa focus)"
echo ""
echo "You can verify by calling: GET ${BASE_URL}"