/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check if the API is running and healthy
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Music Folders
         * @description Scan specified folders for music files and add them to the library
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScanLibraryRequest"];
                };
            };
            responses: {
                /** @description Scan started successfully */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanLibraryResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/scan/{scan_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Status
         * @description Get the current status of a library scan operation
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scan_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Scan status retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tracks
         * @description Get a paginated list of tracks with optional filtering and sorting
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    /** @description Search query for title, artist, or genre */
                    search?: string;
                    genre?: string;
                    mood?: string;
                    bpm_min?: number;
                    bpm_max?: number;
                    key?: string;
                    /** @description Filter by exact artist name */
                    artist?: string;
                    /** @description Minimum year (inclusive) */
                    year_min?: number;
                    /** @description Maximum year (inclusive) */
                    year_max?: number;
                    sort_by?: "title" | "artist" | "bpm" | "key" | "year" | "created_at";
                    sort_order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tracks retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TracksListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add Track Manually
         * @description Manually add a track to the library
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TrackCreate"];
                };
            };
            responses: {
                /** @description Track created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Track
         * @description Get detailed information about a specific track
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    track_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Track retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                /** @description Track not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Update Track
         * @description Update track metadata
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    track_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TrackUpdate"];
                };
            };
            responses: {
                /** @description Track updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete Track
         * @description Remove a track from the library (does not delete the file)
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    track_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Track deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/bulk/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Delete Tracks
         * @description Delete multiple tracks from the library
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkDeleteTracksRequest"];
                };
            };
            responses: {
                /** @description Tracks deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkDeleteTracksResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/{track_id}/reset-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Track Metadata
         * @description Reset track metadata to original values from the audio file. Reads metadata directly from file tags.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the track to reset */
                    track_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResetMetadataRequest"];
                };
            };
            responses: {
                /** @description Metadata reset successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResetMetadataResponse"];
                    };
                };
                /** @description Bad request (e.g., track has no file path) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
                /** @description Track not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
                /** @description Error reading metadata from file */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Track Metadata
         * @description Analyze audio file to extract BPM, key, and other metadata
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnalyzeMetadataRequest"];
                };
            };
            responses: {
                /** @description Metadata analyzed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetadataAnalysis"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/batch-analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Analyze Metadata
         * @description Analyze metadata for multiple tracks
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchAnalyzeMetadataRequest"];
                };
            };
            responses: {
                /** @description Batch analysis started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BatchAnalyzeMetadataResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enhance Track Metadata with AI
         * @description Use AI to fill in missing metadata for a track
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EnhanceMetadataRequest"];
                };
            };
            responses: {
                /** @description Metadata enhanced successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnhanceMetadataResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/batch-enhance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Enhance Multiple Tracks
         * @description Enhance metadata for multiple tracks using AI
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchEnhanceMetadataRequest"];
                };
            };
            responses: {
                /** @description Batch enhancement started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BatchEnhanceMetadataResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Enhancement Job Status
         * @description Check the status of a batch enhancement job
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    job_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job status retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnhancementJobStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Playlists
         * @description Get all playlists
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Playlists retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Playlist"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create Playlist
         * @description Create a new playlist
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePlaylistRequest"];
                };
            };
            responses: {
                /** @description Playlist created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Playlist"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Playlist
         * @description Get playlist details including tracks
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playlist_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Playlist retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaylistDetail"];
                    };
                };
            };
        };
        /**
         * Update Playlist
         * @description Update playlist name or description
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playlist_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePlaylistRequest"];
                };
            };
            responses: {
                /** @description Playlist updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delete Playlist
         * @description Delete a playlist
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playlist_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Playlist deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{playlist_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Tracks to Playlist
         * @description Add one or more tracks to a playlist
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playlist_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddTracksToPlaylistRequest"];
                };
            };
            responses: {
                /** @description Tracks added successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Remove Tracks from Playlist
         * @description Remove tracks from a playlist
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playlist_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RemoveTracksFromPlaylistRequest"];
                };
            };
            responses: {
                /** @description Tracks removed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{playlist_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Playlist
         * @description Export playlist in various formats
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playlist_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExportPlaylistRequest"];
                };
            };
            responses: {
                /** @description Playlist exported successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExportPlaylistResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Library Overview
         * @description Get overall statistics about the music library
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview statistics retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/bpm-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get BPM Distribution
         * @description Get distribution of tracks by BPM ranges
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description BPM distribution retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BPMDistributionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/key-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Key Distribution
         * @description Get distribution of tracks by musical key
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Key distribution retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KeyDistributionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/genre-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Genre Distribution
         * @description Get distribution of tracks by genre
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Genre distribution retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenreDistributionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/mood-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mood Distribution
         * @description Get distribution of tracks by mood
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mood distribution retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MoodDistributionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refdata/{refdata_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reference Data
         * @description Get reference data for filters and other stable values
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Type of reference data to retrieve */
                    refdata_type: components["schemas"]["RefdataType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reference data retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefdataResponse"];
                    };
                };
                /** @description Reference data type not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create or Update Reference Data
         * @description Create or update reference data entries for a specific type and key
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Type of reference data */
                    refdata_type: components["schemas"]["RefdataType"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRefdataRequest"];
                };
            };
            responses: {
                /** @description Reference data created or updated successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateRefdataResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        /**
         * Delete All Reference Data for Type
         * @description Delete all reference data entries for a given type
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Type of reference data to delete */
                    refdata_type: components["schemas"]["RefdataType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reference data deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteRefdataResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Track: {
            /** Format: uuid */
            id?: string;
            title?: string;
            artist?: string;
            album?: string;
            year?: number;
            genre?: string;
            mood?: string;
            bpm?: number;
            key?: string;
            /** @description Duration in seconds */
            duration_seconds?: number;
            file_path?: string;
            /** @description File size in bytes */
            file_size_bytes?: number;
            /** @example mp3 */
            file_format?: string;
            /** @description Bitrate in bits per second */
            bitrate_bps?: number;
            /** @description Sample rate in Hertz (Hz) */
            sample_rate_hz?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            last_played?: string;
            play_count?: number;
            metadata_complete?: boolean;
        };
        TrackCreate: {
            file_path: string;
            title?: string;
            artist?: string;
            album?: string;
            year?: number;
            genre?: string;
            mood?: string;
            bpm?: number;
            key?: string;
        };
        TrackUpdate: {
            title?: string;
            artist?: string;
            album?: string;
            year?: number;
            genre?: string;
            mood?: string;
            bpm?: number;
            key?: string;
        };
        DetectedMetadata: {
            bpm?: number;
            key?: string;
            /** @description Duration in seconds */
            duration_seconds?: number;
            /** @description Sample rate in Hertz (Hz) */
            sample_rate_hz?: number;
            /** @description Bitrate in bits per second */
            bitrate_bps?: number;
        };
        ConfidenceScores: {
            /** Format: float */
            bpm?: number;
            /** Format: float */
            key?: number;
        };
        MetadataAnalysis: {
            file_path?: string;
            detected_metadata?: components["schemas"]["DetectedMetadata"];
            confidence_scores?: components["schemas"]["ConfidenceScores"];
        };
        Playlist: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            track_count?: number;
            /** @description Total duration in seconds */
            total_duration_seconds?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        PlaylistDetail: components["schemas"]["Playlist"] & {
            tracks?: components["schemas"]["Track"][];
        };
        LibraryOverview: {
            total_tracks?: number;
            /** @description Total duration in seconds */
            total_duration_seconds?: number;
            /** @description Total size in bytes */
            total_size_bytes?: number;
            total_genres?: number;
            /** Format: float */
            average_bpm?: number;
            most_common_key?: string;
            /**
             * Format: float
             * @description Percentage of tracks with complete metadata
             */
            metadata_completeness?: number;
            tracks_missing_metadata?: number;
        };
        Pagination: {
            page?: number;
            size?: number;
            total_pages?: number;
            total_items?: number;
            has_next?: boolean;
            has_previous?: boolean;
        };
        TracksListResponse: {
            data?: components["schemas"]["Track"][];
            pagination?: components["schemas"]["Pagination"];
        };
        ScanLibraryRequest: {
            /**
             * @example [
             *       "/Users/username/Music/DJ Collection",
             *       "/Users/username/Downloads"
             *     ]
             */
            paths: string[];
            /** @default true */
            include_subfolders: boolean;
            /** @default true */
            watch_for_changes: boolean;
            /** @default false */
            skip_duplicates: boolean;
        };
        ScanLibraryResponse: {
            /** Format: uuid */
            scan_id?: string;
            /** @example scanning */
            status?: string;
            /** @example Library scan started */
            message?: string;
        };
        HealthResponse: {
            /** @example healthy */
            status?: string;
            /** @example 1.0.0 */
            version?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ScanStatusResponse: {
            /** Format: uuid */
            scan_id?: string;
            /**
             * @description Current status of the scan operation
             * @enum {string}
             */
            status?: "discovering" | "scanning" | "completed" | "failed";
            /**
             * @description Current stage message (e.g., 'Discovering audio files...', 'Processing 100 audio file(s)...')
             * @example Discovering audio files...
             */
            message?: string;
            /**
             * Format: float
             * @description Progress percentage (0-100)
             * @example 75.5
             */
            progress?: number;
            /**
             * @description Total number of files processed
             * @example 1247
             */
            files_scanned?: number;
            /**
             * @description Number of files added to the library
             * @example 1200
             */
            files_added?: number;
            /**
             * @description Number of files skipped (duplicates)
             * @example 47
             */
            files_skipped?: number;
            /** @description List of errors encountered during the scan */
            errors?: string[];
            /**
             * @description List of paths being scanned
             * @example [
             *       "/Users/username/Music",
             *       "/Users/username/Documents/Music"
             *     ]
             */
            paths?: string[];
        };
        BulkDeleteTracksRequest: {
            track_ids?: string[];
        };
        BulkDeleteTracksResponse: {
            deleted_count?: number;
        };
        AnalyzeMetadataRequest: {
            /** @example /path/to/track.mp3 */
            file_path?: string;
            analysis_options?: {
                /** @default true */
                detect_bpm: boolean;
                /** @default true */
                detect_key: boolean;
                /** @default false */
                detect_genre: boolean;
            };
        };
        BatchAnalyzeMetadataRequest: {
            track_ids?: string[];
        };
        BatchAnalyzeMetadataResponse: {
            /** Format: uuid */
            job_id?: string;
            /** @example processing */
            status?: string;
            /** @description List of errors encountered during the batch analysis */
            errors?: string[];
        };
        /** @description Request to reset track metadata to original values from file */
        ResetMetadataRequest: {
            /**
             * @description If true, update the track in the database with original metadata
             * @default false
             */
            update_track: boolean;
        };
        /** @description Response from reset metadata operation */
        ResetMetadataResponse: {
            /** Format: uuid */
            track_id?: string;
            file_path?: string;
            /**
             * @description Original metadata values read from the audio file
             * @example {
             *       "title": "Song Title",
             *       "artist": "Artist Name",
             *       "album": "Album Name",
             *       "year": 2020,
             *       "genre": "Electronic",
             *       "bpm": 128,
             *       "key": "Am"
             *     }
             */
            original_metadata?: {
                [key: string]: unknown;
            };
            /**
             * @description Whether the track was updated in the database
             * @default false
             */
            updated: boolean;
        };
        EnhanceMetadataRequest: {
            /** Format: uuid */
            track_id: string;
            enhancement_options?: {
                /** @default true */
                enhance_genre: boolean;
                /** @default true */
                enhance_mood: boolean;
                /** @default true */
                enhance_bpm: boolean;
                /** @default true */
                enhance_key: boolean;
            };
        };
        EnhanceMetadataResponse: {
            /** Format: uuid */
            track_id?: string;
            enhanced_fields?: {
                genre?: string;
                mood?: string;
                bpm?: number;
                key?: string;
            };
            confidence_scores?: {
                /** Format: float */
                genre?: number;
                /** Format: float */
                mood?: number;
            };
        };
        BatchEnhanceMetadataRequest: {
            track_ids?: string[];
            enhancement_options?: {
                /** @default true */
                enhance_genre: boolean;
                /** @default true */
                enhance_mood: boolean;
            };
        };
        BatchEnhanceMetadataResponse: {
            /** Format: uuid */
            job_id?: string;
            total_tracks?: number;
        };
        EnhancementJobStatus: {
            /** Format: uuid */
            job_id?: string;
            /** @enum {string} */
            status?: "pending" | "processing" | "completed" | "failed";
            /** Format: float */
            progress?: number;
            tracks_processed?: number;
            tracks_total?: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
        };
        CreatePlaylistRequest: {
            /** @example Summer House Mix */
            name: string;
            /** @example High energy house tracks for summer sets */
            description?: string;
        };
        UpdatePlaylistRequest: {
            name?: string;
            description?: string;
        };
        AddTracksToPlaylistRequest: {
            track_ids?: string[];
        };
        RemoveTracksFromPlaylistRequest: {
            track_ids?: string[];
        };
        ExportPlaylistRequest: {
            /**
             * @default m3u
             * @enum {string}
             */
            format: "m3u" | "pls" | "xspf" | "json";
            output_path?: string;
        };
        ExportPlaylistResponse: {
            file_path?: string;
            format?: string;
        };
        BPMDistributionResponse: {
            distribution?: {
                /** @example 120-140 */
                range?: string;
                count?: number;
                /** Format: float */
                percentage?: number;
            }[];
        };
        KeyDistributionResponse: {
            distribution?: {
                /** @example Am */
                key?: string;
                count?: number;
                /** Format: float */
                percentage?: number;
            }[];
        };
        GenreDistributionResponse: {
            distribution?: {
                genre?: string;
                count?: number;
                /** Format: float */
                percentage?: number;
            }[];
        };
        MoodDistributionResponse: {
            distribution?: {
                mood?: string;
                count?: number;
                percentage?: number;
            }[];
        };
        /**
         * @description Available reference data types. Can be extended with additional types as the project grows.
         * @example trackfilters
         * @enum {string}
         */
        RefdataType: "trackfilters";
        /** @description A single key-value pair in reference data */
        RefdataItem: {
            /** @description The filter category name (e.g., 'genre', 'mood') */
            key: string;
            /** @description List of filter options for this category */
            value: string[];
        };
        /** @description Reference data response as an array of key-value pairs */
        RefdataResponse: {
            /** @description Array of reference data categories with their options */
            data: components["schemas"]["RefdataItem"][];
        };
        /** @description Request schema for creating or updating reference data */
        CreateRefdataRequest: {
            /** @description The filter category name (e.g., 'genre', 'mood') */
            key: string;
            /** @description List of values to store for this key */
            value: string[];
        };
        /** @description Response schema for creating reference data */
        CreateRefdataResponse: {
            /** @description The reference data type */
            type: string;
            /** @description The filter category name */
            key: string;
            /** @description Number of new entries created */
            created_count: number;
            /** @description Number of existing entries updated */
            updated_count: number;
        };
        /** @description Response schema for deleting reference data */
        DeleteRefdataResponse: {
            /** @description The reference data type */
            type: string;
            /** @description The filter category name */
            key: string;
            /** @description Number of entries deleted */
            deleted_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
